### ISSUE TITLE
API Deprecation

### ISSUE THREAD

**Issue by alexburley** [DynamoSoftware/DynamoAPI#7]
Hello,

Is there a timeline for when version 1 will be disabled on existing distributions?

Thanks

**Comment by de0xyrib0se** [comment]
Alex, we plan on disabling it on existing distributions end of this year.

Only v2.0 should be used.

Also, there are no callbacks nor notifications built into the API, so any requests of IFTTT nature would need to be initiated externally through some kind of scheduling.

**Comment by de0xyrib0se** [comment]
Archive
